<?php
/**
 * Simple Icons name mappings.
 *
 * This file is auto-generated by static/js/simpleicons.js
 *
 * @package IndieWeb
 */

/**
 * Get the mapping of icon slugs to display names.
 *
 * @return array Array of icon slug => display name pairs.
 */
function simpleicons_iw_get_names() {
	return array(
		'500px'         => '500px',
		'activitypub'   => 'ActivityPub',
		'adobe'         => 'Adobe',
		'applemusic'    => 'Apple Music',
		'applepodcasts' => 'Apple Podcasts',
		'bandcamp'      => 'Bandcamp',
		'behance'       => 'Behance',
		'bitcoin'       => 'Bitcoin',
		'blogger'       => 'Blogger',
		'bluesky'       => 'Bluesky',
		'buymeacoffee'  => 'Buy Me A Coffee',
		'codepen'       => 'CodePen',
		'codeberg'      => 'Codeberg',
		'diaspora'      => 'Diaspora',
		'discord'       => 'Discord',
		'dribbble'      => 'Dribbble',
		'element'       => 'Element',
		'ethereum'      => 'Ethereum',
		'etsy'          => 'Etsy',
		'facebook'      => 'Facebook',
		'figma'         => 'Figma',
		'flickr'        => 'Flickr',
		'flipboard'     => 'Flipboard',
		'github'        => 'GitHub',
		'gitlab'        => 'GitLab',
		'gitea'         => 'Gitea',
		'goodreads'     => 'Goodreads',
		'googlechat'    => 'Google Chat',
		'googleplay'    => 'Google Play',
		'gravatar'      => 'Gravatar',
		'gumroad'       => 'Gumroad',
		'instagram'     => 'Instagram',
		'keybase'       => 'Keybase',
		'kofi'          => 'Ko-fi',
		'lastdotfm'     => 'Last.fm',
		'lemmy'         => 'Lemmy',
		'letterboxd'    => 'Letterboxd',
		'linkedin'      => 'LinkedIn',
		'mastodon'      => 'Mastodon',
		'matrix'        => 'Matrix',
		'medium'        => 'Medium',
		'microdotblog'  => 'Micro.blog',
		'misskey'       => 'Misskey',
		'orcid'         => 'ORCID',
		'patreon'       => 'Patreon',
		'paypal'        => 'PayPal',
		'peertube'      => 'PeerTube',
		'pinterest'     => 'Pinterest',
		'pixelfed'      => 'Pixelfed',
		'pleroma'       => 'Pleroma',
		'pocket'        => 'Pocket',
		'rss'           => 'RSS',
		'reddit'        => 'Reddit',
		'signal'        => 'Signal',
		'slack'         => 'Slack',
		'snapchat'      => 'Snapchat',
		'soundcloud'    => 'SoundCloud',
		'spotify'       => 'Spotify',
		'stackoverflow' => 'Stack Overflow',
		'strava'        => 'Strava',
		'stripe'        => 'Stripe',
		'substack'      => 'Substack',
		'swarm'         => 'Swarm',
		'telegram'      => 'Telegram',
		'threads'       => 'Threads',
		'tiktok'        => 'TikTok',
		'tumblr'        => 'Tumblr',
		'twitch'        => 'Twitch',
		'vimeo'         => 'Vimeo',
		'whatsapp'      => 'WhatsApp',
		'wordpress'     => 'WordPress',
		'x'             => 'X',
		'ycombinator'   => 'Y Combinator',
		'youtube'       => 'YouTube',
		'zoom'          => 'Zoom',
		'npm'           => 'npm',
	);
}
